server:
  port: 8080
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/adso_thymeleaf
    username: root
    password: b3192621119B
    jpa:
      hibernate:
        ddl-auto: update